name: FTP Deploy

on:
  push:
    branches:
      - master

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›’ Checkout
        uses: actions/checkout@v3

      - name: âš™ï¸ Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: ğŸ“¦ Cache node_modules
        uses: actions/cache@v2
        id: cache
        with:
          path: '**/frontend/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: ğŸ’¿ Install
        run: npm ci -f
        working-directory: ./frontend

      - name: ğŸ’¾ Configure Client
        run: |
          echo "REACT_APP_API_HOST = '${{ secrets.CLIENT_API_HOST }}'
          REACT_APP_METRIKA = ' '" > .env
        working-directory: ./frontend

      - name: ğŸ‘·â€ Build UI
        run: |
          export dateNow=$(date +"%d.%m.%Y")
          echo "export const update = '$dateNow';" > src/update.ts
          npm run build --if-present
        working-directory: ./frontend

      - name: ğŸ“¦ Get LFTP
        run: sudo apt install lftp

      - name: ğŸ› ï¸ Configure LFTP
        run: mkdir ~/.lftp && echo "set ssl:verify-certificate false;" >> ~/.lftp/rc

      - name: ğŸ”‘ Load Secrets
        run: echo "machine ${{ secrets.FTP_HOSTNAME }} login ${{ secrets.FTP_USERNAME }} password ${{ secrets.FTP_PASSWORD }}" > ~/.netrc

      - name: ğŸ“ Upload Folder
        run: lftp -e "mirror --parallel=100 -R frontend/build/ /" ${{ secrets.FTP_HOSTNAME }}
